# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


resources:
 pipelines:
   - pipeline: foobar
     source: jainamanjain.pipelines-java

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Job1
    steps:
    - download: foobar
      artifact: A1
    - powershell: |
        ls $(Pipeline.Workspace)/

- stage: deployment
  jobs:
    - deployment: Deploy1
      pool: hosted
      environment: Env01
      strategy:
        runOnce:
          deploy:
            steps:
            - powershell: |
                ls $(Pipeline.workspace)/
    
    - deployment: Deploy2
      pool: hosted
      environment: Env01
      strategy:
        runOnce:
          deploy:
            steps:
            - download: foobar
              artifact: A2
            - powershell: |
                ls $(Pipeline.workspace)/
